### ISSUE TITLE
strange bug 

### ISSUE THREAD

**Issue by pylat** [kul-forbes/PANOC.jl#1]
Hi Stella. I have a question. I am trying to use your iterative method tool. I am getting a really weird bug that I can't figure out. I have been trying to isolate the bug. So to demonstrate, in the following code I first solve your tiny lasso problem with AFBA, and then try to solve the same problem with another iteration (named finito).  

```
x0 = ones(n); y0 = randn(n)
it, xAFBA, y, sol = ProximalAlgorithms.AFBA(x0, y0; g=g, f=f, betaQ =Lf, theta=2,mu=1,maxit=10000, tol=1e-12)
println("the solution via AFBA is $xAFBA")
 u = copy(xAFBA)
x_finito, it_finito = finito(f, g, x0, L=Lf, N=1, alpha =0.95, maxit=10000, tol=1e-10, verbose=true, freq=1)   
println("finito's solution is $x_finito")
println("$xAFBA")
println("$u")
```
what is happening is that xAFBA as the solution of AFBA is assigned some value. But once I run the code for the second solver (finito), the value of xAFBA is being changed to that of finito somehow. I really don't see how this is possible. There is zero mention of xAFBA in the line calling finito. Also if I copy xAFBA into u, u remains as the solution of AFBA and doesn't change. 

Any ideas what could be causing this? 
  
One thing which may be relevant is that in your Panoc code at line 192 you write `return nothing`. Why this and not `return state, state`? What am I missing? 
By the way I am using Julia 1.1.0.

**Comment by lostella** [comment]
After running AFBA, try doing 
```julia
objectid(x0) == objectid(xAFBA)
```
If I'm not wrong, the current implementation overwrites the initial point with the solution as well, so the above line should return `True`. Then you use `x0` as initial point when calling `finito`: if also there you overwrite the initial point, i.e. if
```julia
objectid(x0) == objectid(x_finito)
```
then this explains it.

**Comment by pylat** [comment]
yep that was it. Thanks Stella.

**Comment by lostella** [comment]
@pylat FYI: this package (PANOC.jl) was mostly a proof-of-concept to try re-implementing algorithms using these iterative method tools (iterables) as you noticed. Since this way of doing things looked pretty nice to me, I started migrating all algorithms in ProximalAlgorithms to this setting, see https://github.com/kul-forbes/ProximalAlgorithms.jl/pull/18: once I'll be finished there (this is hopefully a matter of days) I will
1. Ask you to review the changes in that PR (especially wrt the primal-dual stuff);
2. Deprecate this package (since PANOC is also there).

**Comment by pylat** [comment]
Sure. Indeed this iterative method tools are pretty nice. Now I am implementing some other block-coordinate algorithm using it. We may consider adding it there too at some point.
